### PR TITLE
fix alt tag handling

### PR DESCRIPTION
**Pull request by modosc**
1. pass `imgProps` down to `` tags auto-generated by `type=picture` - previously this was done as a spread assignment since `className` and `styles` were the only `imgProps` we cared about (and we wanted to set those directly on the newly created `<Imgix>` component rather than its `` child). 
2. strip `alt` props from `<picture>` and `<source`> tags since they're not allowed. 
3. update deps

### CODE REVIEW

**Comment by modosc** [comment]
@frederickfogerty you ok if i merge this?

**Comment by frederickfogerty** [comment]
@modosc sorry for the delay, must've slipped through the cracks. 

This looks great, thanks! 🙌🏿

**Comment by modosc** [comment]
thanks @frederickfogerty , can you roll up a release?

**Comment by frederickfogerty** [comment]
Is this a breaking change @modosc?

**Comment by modosc** [comment]
> Is this a breaking change @modosc?

nope, a bugfix

**Comment by frederickfogerty** [comment]
Published as `6.0.1` @modosc. Thanks again 🙌🏿

**Pull request merged**
