### PR TITLE
remove deprecated bg prop, update deps to react >= 15

### PR DESCRIPTION
**Pull request by modosc**

### CODE REVIEW

**Comment by frederickfogerty** [comment]
@modosc thanks for doing this, and apologies for dropping the ball on this. 

I'm going to edit the CHANGELOG slightly, but otherwise, this is exactly what I wanted.

Should I pull in your other PR before this one, so we can roll it into one release?

**Comment by modosc** [comment]
> Should I pull in your other PR before this one, so we can roll it into one release?

yes please!

**Comment by frederickfogerty** [comment]
@modosc cool, I've merged the other PR. Can you please resolve the conflicts 😢, and make sure prettier is run (using `npm run pretty`). 

Thank you so much for your help 🙌🏿

**Comment by modosc** [comment]
ok, should be good?

**Comment by frederickfogerty** [comment]
Published, thanks @modosc!

**Pull request merged**
