### PR TITLE
Better child props

### PR DESCRIPTION
**Pull request by frederickfogerty**
Change child props behaviour to only pass down props not used, not every prop

- as a bonus, we no longer have to delete child props!

### CODE REVIEW

**Comment by frederickfogerty** [comment]
When #10 is merged, this can be rebased and the tests will pass

**Comment by paulstraw** [comment]
Happy to handle this one now that #10 is merged, if you'd like.

**Comment by frederickfogerty** [comment]
@paulstraw just rebased, tests should pass

**Comment by paulstraw** [comment]
Nifty, thanks @frederickfogerty. :grin:

**Pull request merged**
