### PR TITLE
feat: add support for customizing srcset generation

### PR DESCRIPTION
**Pull request by cecchi**
## Description

This PR closes https://github.com/imgix/react-imgix/issues/723.

This adds support for controlling how the `srcset` attribute is generated, exposing the options supported by [ImgixClient.buildSrcSet](https://github.com/imgix/js-core#imgixclientbuildsrcsetpath-params-options): 

 - `widths`
 - `widthTolerance`
 - `minWidth`
 - `maxWidth`

I prefixed each option's equivalent prop with `srcSet` to make the purpose clear. I did not add one for `disableVariableQuality` since that is already controlled by the `disableQualityByDPR` prop.

Our use-case is that the generated `srcset` attributes are larger and overly granular than what we reasonably need. We have ~zero users who need 5000px wide images, and few source images that are large enough to render effectively at that size anyway. The size of the generated HTML can add up: a single srcset attribute is roughly 4kb when using the default settings. When rendering potentially hundreds of images on a single page, the total size is not trivial. These repetitive strings gzip very efficiently, but it's still unnecessary markup we'd rather do without.

## Checklist

I have not written documentation or tests for this feature yet, but am happy to if there is not opposition to the addition of these props in the first place. This change is backwards compatible.

- [x] Run unit tests to ensure all existing tests are still passing
- [x] Add new passing unit tests to cover the code introduced by your PR
- [x] Update the readme
- [ ] Add some [steps](#steps-to-test) so we can test your cool new feature!
- [x] The PR title is in the [conventional commit](#conventional-commit-spec) format: e.g. `feat(<area>): added new way to do this cool thing #issue-number`
- [ ] Add your info to the [contributors](#packagejson-contributors) array in package.json!

## Steps to Test

I do not have a simple test repo, but this should be trivial to test by checking out the branch locally, building, and linking to any existing app using `react-imgix`. Usage looks like:

```tsx
<Image
  src="https://assets.imgix.net/unsplash/bear.jpg"
  srcSetOptions={{
   widthTolerance: 0.15,
   maxWidth: 3000
  }}
/>
```

### CODE REVIEW

**Comment by sherwinski** [comment]
Thanks for the PR @cecchi! We're definitely in favor of surfacing these options to users but let me take this back to the team for some discussion and see if there are any strong opinions on the interface. I'll get back to you sometime in the next week on how we'd like to proceed.

**Comment by cecchi** [comment]
Hi @sherwinski, any updates from your team?

**Comment by sherwinski** [comment]
Hey @cecchi ,
After discussing with the team, the major feedback given was that we'd prefer to contain these options within an object such as `srcsetOptions` rather than individual top-level props. If you don't mind making that adjustment, then we can move forward with writing tests and docs as well. I'm happy to answer any questions or provide guidance as needed 👍

**Comment by cecchi** [comment]
Thanks @sherwinski. I've updated the PR with the proposed API, and added tests and some documentation to the README. I opted to link to the `@imgix/js-core` docs rather than redocument the options here, but feel free to update the docs however you feel is best.

**Comment by frederickfogerty** [comment]
Hey @cecchi, thanks for the PR here! There are a few things to be changed before merging but overall this looks good, so I've gone ahead and done that in #807 since I couldn't push any changes to your fork/this PR. That PR will merge once the tests pass 👍

**Pull request closed without merging**
