### PR TITLE
Rename `aggresiveLoad` to `aggressiveLoad`.

### LINKED ISSUE #23: agressiveLoad typo
There seems to be a mismatch in code and docs:

*in the docs*
`aggressiveLoad={bool}`

*in the code*
`aggresiveLoad: false`
https://github.com/imgix/react-imgix/blob/master/src/index.js#L45

### PR DESCRIPTION
**Pull request by paulstraw**
Fixes #23

### CODE REVIEW

**Comment by ekosz** [comment]
Yep, that's the correct spelling all right. 👍 I'll be sure to upgrade to 3.0 when it hits.

**Comment by paulstraw** [comment]
Good work, team. Great eng effort.

**Comment by KristerV** [comment]
nice

**Comment by frederickfogerty** [comment]
Great work team, such a big change here. 😂

**Pull request merged**
