### PR TITLE
SUPPORT-531 : Clarifies `Imgix` casing

### PR DESCRIPTION
**Pull request by heyitsbryanm**
## Description

Clarifies casing around Imgix by formatting it as a component. Also adds links to our rendering API.

```
When width and height are specified, Imgix will give the image a srcset with resolution descriptors.
```

```
When width and height are specified, `<Imgix>` will give the image a srcset with resolution descriptors.
```

## Checklist

- [ ] Read the [contributing guidelines](CONTRIBUTING.md).
- [ ] Each commit follows the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) spec format.
- [ ] Update the readme (if applicable).
- [ ] Update or add any necessary API documentation (if applicable)
- [ ] All existing unit tests are still passing (if applicable).

- [ ] Add some [steps](#steps-to-test) so we can test your bug fix or feature (if applicable).
- [ ] Add new passing unit tests to cover the code introduced by your PR (if applicable).
- [ ] Any breaking changes are specified on the commit on which they are introduced with `BREAKING CHANGE` in the body of the commit.
- [ ] If this is a big feature with breaking changes, consider opening an issue to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.

### CODE REVIEW

**Comment by heyitsbryanm** [comment]
For small readme changes like this, do we need to update and release a new version?

**Comment by heyitsbryanm** [comment]
Also, the tests are failing due to ChromeDriver

**Comment by luqven** [comment]
> For small readme changes like this, do we need to update and release a new version?

No there's no need. We typically use `docs:` commit and let semantic-release take care of it anyway.

Right now the automated release step is having issues because of failing tests as you mentioned. I'll circle back on the failing CI steps next week.

**Review by luqven — APPROVED** [review]

**Comment by heyitsbryanm** [comment]
Wooo figured it out. It was an issue with browser-tools:
https://github.com/cypress-io/circleci-orb/issues/446

I updated it in [Arno's PR](https://github.com/imgix/react-imgix/pull/945) and that automerged it.

I rebased my branch and it's working here too now.

**Comment by luqven** [comment]
> Wooo figured it out. It was an issue with browser-tools

Perfect, and thanks for opening that PR. Approved!

**Pull request merged**
